# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: velyx
description: Sistema focado em performance e jogos.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - gamescope
      - mangohud
      - goverlay
      - steam-devices
      - fastfetch
      - gamemode

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - org.mozilla.firefox

  - type: script
    scripts:
      - post-install.sh

  - type: signing
